### ISSUE TITLE
The rule pertaining to what constitutes as a die.

### ISSUE THREAD

**Issue by OceanOSdev** [jacobthehammer/Nomic#1]
It seems it didn't copy the LaTeX that was in the original rule.

**Comment by jacobthehammer** [comment]
It wouldn't be compatible with Discord markdown. We can fix it by using unicode characters in place of LaTeX.

**Comment by jacobthehammer** [comment]
Fixed in [df31569](https://github.com/jacobthehammer/Nomic/commit/df315696c23e28ffd4b4cae292535bcfe73d17a4)
